### PR TITLE
adding support for 1.8(.8)

### PR DESCRIPTION
**Pull request by TheSnoozer**
Hi, great plugin.
I added support for 1.8(.8) :-)
The file v1_8_R3/src/main/java/com/github/teozfrank/duelme/nms/v1_8_R3/NMSHandler.java is basically a copy from v1_9_R2 with the 'v1_9_R2' replaced accordingly.

Thanks,

### CODE REVIEW

**Comment by teozfrank** [comment]
Have you tested this out? Will add later when I get a chance to look at the code.

**Comment by TheSnoozer** [comment]
Hi, it's working for me locally with a spigot 1.8.8 server :-)

**Comment by teozfrank** [comment]
Great just merged will pull the changes and release soon thank you.

**Comment by TheSnoozer** [comment]
Thanks :-)

**Comment by NegroBallz** [comment]
Guys where can i download the 1.8 version?

**Comment by NZSwAg40** [comment]
^Where can I download this version that supports 1.8.8 ?

**Pull request merged**
